services:
  writehat:
    command: bash -c "
      sleep 2 &&
      ./manage.py makemigrations writehat &&
      ./manage.py migrate writehat &&
      ./manage.py makemigrations &&
      ./manage.py migrate &&
      uwsgi --http 0.0.0.0:8000 --static-map /static=/opt/writehat/static --plugin-dir=/usr/lib/uwsgi/plugins --plugin python3 -w writehat.wsgi:application --processes=2 --master --vacuum --py-autoreload 1"
    environment:
      - PYTHONPATH=/opt
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
