# Generated by Django 3.1.14 on 2026-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writehat', '0002_cvss4_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tlpDisplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='tlpLevel',
            field=models.CharField(choices=[('CLEAR', 'TLP:CLEAR'), ('GREEN', 'TLP:GREEN'), ('AMBER', 'TLP:AMBER'), ('AMBER+STRICT', 'TLP:AMBER+STRICT'), ('RED', 'TLP:RED')], default='CLEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='tlpDisplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='tlpLevel',
            field=models.CharField(choices=[('CLEAR', 'TLP:CLEAR'), ('GREEN', 'TLP:GREEN'), ('AMBER', 'TLP:AMBER'), ('AMBER+STRICT', 'TLP:AMBER+STRICT'), ('RED', 'TLP:RED')], default='CLEAR', max_length=20),
        ),
    ]
