# Generated by Django 3.1.14 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writehat', '0003_report_tlp_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='defaultLanguage',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='defaultLanguage',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=8),
        ),
    ]
