# Generated by Django 3.1.14 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writehat', '0004_report_default_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvssfindinggroup',
            name='prefix',
            field=models.CharField(blank=True, default='T', max_length=50, null=True, verbose_name='Finding Prefix'),
        ),
        migrations.AlterField(
            model_name='cvss4findinggroup',
            name='prefix',
            field=models.CharField(blank=True, default='T4', max_length=50, null=True, verbose_name='Finding Prefix'),
        ),
        migrations.AlterField(
            model_name='dreadfindinggroup',
            name='prefix',
            field=models.CharField(blank=True, default='NT', max_length=50, null=True, verbose_name='Finding Prefix'),
        ),
        migrations.AlterField(
            model_name='proactivefindinggroup',
            name='prefix',
            field=models.CharField(blank=True, default='P', max_length=50, null=True, verbose_name='Finding Prefix'),
        ),
    ]
